version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgresUser"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    networks:
      - app-tier
  phpfpm:
    tty: true
    stdin_open: true
    image: bitnami/php-fpm:7.3
    networks:
      - app-tier
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: "serverName=test07_server"
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    image: bitnami/nginx:latest
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - "80:80"
    volumes:
      - ./nginx_config_project07.conf:/opt/bitnami/nginx/conf/server_blocks/yourapp.conf
