version: "3.7"
networks:
  app-tier:
    driver: bridge
services:
  postgres:
    image: postgres:13.3
    restart: always
    networks:
      - app-tier
  phpfpm:
    tty: true
    stdin_open: true
    # image: bitnami/php-fpm:7.3
    networks:
      - app-tier
    volumes:
      #- ./src:/app/src
      #- ./migrations:/app/migrations
      #- ./templates:/app/templates
      #- ./config:/app/config
      - ./:/app
    environment:
      PHP_IDE_CONFIG: "serverName=test07_server"
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
  nginx:
    image: bitnami/nginx:latest
    depends_on:
      - phpfpm
    networks:
      - app-tier
    volumes:
      - ./docker/nginx/nginx_config_project07.conf:/opt/bitnami/nginx/conf/server_blocks/project07.conf
      - ./static:/app/static
